Call super() before accessing "mailman" attribute in filebased backend
This fixes:

    Traceback (most recent call last):
      [...]
        app.mail.send(msg)
      File ".../lib64/python3.6/site-packages/flask_mailman/__init__.py", line 76, in send
        mail.connection = self.get_connection(fail_silently=fail_silently)
      File ".../lib64/python3.6/site-packages/flask_mailman/__init__.py", line 62, in get_connection
        return klass(mailman=mailman, fail_silently=fail_silently, **kwds)
      File ".../lib64/python3.6/site-packages/flask_mailman/backends/filebased.py", line 22, in __init__
        self.file_path = self.mailman.file_path
    AttributeError: 'EmailBackend' object has no attribute 'mailman'

Namely, since filebased.EmailBackend() is not instantiated with a
'file_path' argument from _MailMixin.get_connection(), the 'file_path'
attribute in the former class is retrieved from the 'mailman' attribute
which is set in parent class's __init__. By calling super() early, we
make sure the 'mailman' attribute will be set.